using System.Globalization;
using System.Text;
using Site.DesignTokens.Models;
using Site.DesignTokens.Responsive;
using Site.DesignTokens.Values;

namespace Site.DesignTokens.Css;

public sealed class DesignTokenCssGenerator : IDesignTokenCssGenerator
{
    private readonly DesignTokenBreakpointOptions _breakpointOptions;

    public DesignTokenCssGenerator(DesignTokenBreakpointOptions? breakpointOptions = null)
    {
        _breakpointOptions = breakpointOptions ?? new DesignTokenBreakpointOptions();
    }

    public DesignTokenCssGenerationResult Generate(DesignTokenRegistry registry, string selector = ":root", bool includeHeader = true)
    {
        ArgumentNullException.ThrowIfNull(registry);
        selector = string.IsNullOrWhiteSpace(selector) ? ":root" : selector.Trim();

        var errors = new List<DesignTokenCssGenerationError>();
        var rootDeclarations = new List<KeyValuePair<string, string>>();
        var mediaDeclarations = new Dictionary<int, List<KeyValuePair<string, string>>>();

        foreach (var token in registry.All.OrderBy(x => x.Path.Value, StringComparer.Ordinal))
        {
            if (!TryBuildDeclarations(token, rootDeclarations, mediaDeclarations, errors))
            {
                continue;
            }
        }

        if (errors.Count > 0)
        {
            return new DesignTokenCssGenerationResult(string.Empty, errors);
        }

        var builder = new StringBuilder();
        if (includeHeader)
        {
            builder.AppendLine("/*");
            builder.AppendLine(" * Generated design tokens.");
            builder.AppendLine(" * Do not edit this file directly.");
            builder.AppendLine(" */");
            builder.AppendLine();
        }

        builder.Append(selector).AppendLine(" {");

        foreach (var declaration in rootDeclarations.OrderBy(x => x.Key, StringComparer.Ordinal))
        {
            builder.Append("  ")
                .Append(declaration.Key)
                .Append(": ")
                .Append(declaration.Value)
                .AppendLine(";");
        }

        builder.AppendLine("}");

        foreach (var mediaGroup in mediaDeclarations.OrderBy(x => x.Key))
        {
            builder.AppendLine();
            builder.Append("@media (min-width: ")
                .Append(mediaGroup.Key.ToString(CultureInfo.InvariantCulture))
                .AppendLine("px) {");
            builder.Append("  ").Append(selector).AppendLine(" {");

            foreach (var declaration in mediaGroup.Value.OrderBy(x => x.Key, StringComparer.Ordinal))
            {
                builder.Append("    ")
                    .Append(declaration.Key)
                    .Append(": ")
                    .Append(declaration.Value)
                    .AppendLine(";");
            }

            builder.AppendLine("  }");
            builder.AppendLine("}");
        }

        return new DesignTokenCssGenerationResult(builder.ToString(), errors);
    }

    private bool TryBuildDeclarations(
        DesignToken token,
        List<KeyValuePair<string, string>> rootDeclarations,
        Dictionary<int, List<KeyValuePair<string, string>>> mediaDeclarations,
        List<DesignTokenCssGenerationError> errors)
    {
        if (token.ResolvedValue is null)
        {
            errors.Add(new DesignTokenCssGenerationError(token.Path.Value, "Token has no resolved value."));
            return false;
        }

        if (!DesignTokenCssVariableName.TryCreate(token, out var baseName, out var nameError))
        {
            errors.Add(new DesignTokenCssGenerationError(token.Path.Value, nameError));
            return false;
        }

        switch (token.Type)
        {
            case DesignTokenType.Color:
                return TryAddSimpleDeclaration(token, baseName, token.ResolvedValue as ColorTokenValue, x => x.Value, rootDeclarations, errors);

            case DesignTokenType.Dimension:
                return TryAddDimensionDeclarations(token, baseName, token.ResolvedValue, rootDeclarations, mediaDeclarations, errors, _breakpointOptions);

            case DesignTokenType.FontFamily:
                return TryAddSimpleDeclaration(token, baseName, token.ResolvedValue as FontFamilyTokenValue, x => x.Value, rootDeclarations, errors);

            case DesignTokenType.FontWeight:
                return TryAddSimpleDeclaration(token, baseName, token.ResolvedValue as FontWeightTokenValue, x => FormatDecimal(x.Value), rootDeclarations, errors);

            case DesignTokenType.Duration:
                return TryAddSimpleDeclaration(token, baseName, token.ResolvedValue as DurationTokenValue, FormatDurationTokenValue, rootDeclarations, errors);

            case DesignTokenType.Number:
                return TryAddSimpleDeclaration(token, baseName, token.ResolvedValue as NumberTokenValue, x => FormatDecimal(x.Value), rootDeclarations, errors);

            case DesignTokenType.Typography:
                return TryAddTypographyDeclarations(token, baseName, token.ResolvedValue as TypographyTokenValue, rootDeclarations, errors);

            case DesignTokenType.Shadow:
                return TryAddShadowDeclaration(token, baseName, token.ResolvedValue as ShadowTokenValue, rootDeclarations, errors);

            case DesignTokenType.Border:
                return TryAddBorderDeclarations(token, baseName, token.ResolvedValue as BorderTokenValue, rootDeclarations, errors);

            default:
                errors.Add(new DesignTokenCssGenerationError(token.Path.Value, $"Unsupported token type '{token.Type}'."));
                return false;
        }
    }

    private static bool TryAddSimpleDeclaration<TValue>(
        DesignToken token,
        string baseName,
        TValue? value,
        Func<TValue, string?> formatter,
        List<KeyValuePair<string, string>> declarations,
        List<DesignTokenCssGenerationError> errors)
        where TValue : class
    {
        if (value is null)
        {
            errors.Add(new DesignTokenCssGenerationError(token.Path.Value, $"Resolved value type does not match token type '{token.Type}'."));
            return false;
        }

        var cssValue = formatter(value);
        if (string.IsNullOrWhiteSpace(cssValue))
        {
            errors.Add(new DesignTokenCssGenerationError(token.Path.Value, "Resolved value could not be formatted as CSS."));
            return false;
        }

        declarations.Add(new KeyValuePair<string, string>(baseName, cssValue));
        return true;
    }

    private static bool TryAddDimensionDeclarations(
        DesignToken token,
        string baseName,
        object resolvedValue,
        List<KeyValuePair<string, string>> rootDeclarations,
        Dictionary<int, List<KeyValuePair<string, string>>> mediaDeclarations,
        List<DesignTokenCssGenerationError> errors,
        DesignTokenBreakpointOptions breakpointOptions)
    {
        switch (resolvedValue)
        {
            case DimensionTokenValue staticValue:
                return TryAddSimpleDeclaration(token, baseName, staticValue, FormatDimensionTokenValue, rootDeclarations, errors);

            case ResponsiveDimensionTokenValue responsiveValue:
                return TryAddResponsiveDimensionDeclarations(token, baseName, responsiveValue, rootDeclarations, mediaDeclarations, errors, breakpointOptions);

            default:
                errors.Add(new DesignTokenCssGenerationError(token.Path.Value, "Resolved value type does not match token type 'Dimension'."));
                return false;
        }
    }

    private static bool TryAddResponsiveDimensionDeclarations(
        DesignToken token,
        string baseName,
        ResponsiveDimensionTokenValue value,
        List<KeyValuePair<string, string>> rootDeclarations,
        Dictionary<int, List<KeyValuePair<string, string>>> mediaDeclarations,
        List<DesignTokenCssGenerationError> errors,
        DesignTokenBreakpointOptions breakpointOptions)
    {
        var baseValue = value.Mobile ?? value.Tablet ?? value.Desktop;
        if (baseValue is null)
        {
            errors.Add(new DesignTokenCssGenerationError(token.Path.Value, "Responsive dimension token is missing all breakpoint values."));
            return false;
        }

        rootDeclarations.Add(new KeyValuePair<string, string>(baseName, FormatDimensionValue(baseValue)));

        var previousEmitted = baseValue;
        var tabletValue = value.Tablet ?? value.Mobile ?? value.Desktop;
        var desktopValue = value.Desktop ?? value.Tablet ?? value.Mobile;

        if (tabletValue is not null && !DimensionsEqual(tabletValue, previousEmitted))
        {
            AddMediaDeclaration(mediaDeclarations, breakpointOptions.TabletMinWidthPx, baseName, FormatDimensionValue(tabletValue));
            previousEmitted = tabletValue;
        }

        if (desktopValue is not null && !DimensionsEqual(desktopValue, previousEmitted))
        {
            AddMediaDeclaration(mediaDeclarations, breakpointOptions.DesktopMinWidthPx, baseName, FormatDimensionValue(desktopValue));
        }

        return true;
    }

    private static bool TryAddTypographyDeclarations(
        DesignToken token,
        string baseName,
        TypographyTokenValue? value,
        List<KeyValuePair<string, string>> declarations,
        List<DesignTokenCssGenerationError> errors)
    {
        if (value is null)
        {
            errors.Add(new DesignTokenCssGenerationError(token.Path.Value, "Resolved value type does not match token type 'Typography'."));
            return false;
        }

        if (string.IsNullOrWhiteSpace(value.FontFamily) ||
            value.FontWeight is null ||
            value.FontSize is null ||
            value.LineHeight is null)
        {
            errors.Add(new DesignTokenCssGenerationError(token.Path.Value, "Typography token is missing required values."));
            return false;
        }

        declarations.Add(new KeyValuePair<string, string>($"{baseName}-font-family", value.FontFamily));
        declarations.Add(new KeyValuePair<string, string>($"{baseName}-font-weight", FormatDecimal(value.FontWeight)));
        declarations.Add(new KeyValuePair<string, string>($"{baseName}-font-size", FormatDimensionValue(value.FontSize)));
        declarations.Add(new KeyValuePair<string, string>($"{baseName}-line-height", FormatDecimal(value.LineHeight)));

        if (value.LetterSpacing is not null)
        {
            declarations.Add(new KeyValuePair<string, string>($"{baseName}-letter-spacing", FormatDimensionValue(value.LetterSpacing)));
        }

        return true;
    }

    private static bool TryAddShadowDeclaration(
        DesignToken token,
        string baseName,
        ShadowTokenValue? value,
        List<KeyValuePair<string, string>> declarations,
        List<DesignTokenCssGenerationError> errors)
    {
        if (value is null)
        {
            errors.Add(new DesignTokenCssGenerationError(token.Path.Value, "Resolved value type does not match token type 'Shadow'."));
            return false;
        }

        if (string.IsNullOrWhiteSpace(value.Color) ||
            value.OffsetX is null ||
            value.OffsetY is null ||
            value.Blur is null ||
            value.Spread is null)
        {
            errors.Add(new DesignTokenCssGenerationError(token.Path.Value, "Shadow token is missing required values."));
            return false;
        }

        var shorthand = string.Join(
            " ",
            [
                FormatDimensionValue(value.OffsetX),
                FormatDimensionValue(value.OffsetY),
                FormatDimensionValue(value.Blur),
                FormatDimensionValue(value.Spread),
                value.Color
            ]);

        declarations.Add(new KeyValuePair<string, string>(baseName, shorthand));
        return true;
    }

    private static bool TryAddBorderDeclarations(
        DesignToken token,
        string baseName,
        BorderTokenValue? value,
        List<KeyValuePair<string, string>> declarations,
        List<DesignTokenCssGenerationError> errors)
    {
        if (value is null)
        {
            errors.Add(new DesignTokenCssGenerationError(token.Path.Value, "Resolved value type does not match token type 'Border'."));
            return false;
        }

        if (value.Width is null ||
            string.IsNullOrWhiteSpace(value.Style) ||
            string.IsNullOrWhiteSpace(value.Color))
        {
            errors.Add(new DesignTokenCssGenerationError(token.Path.Value, "Border token is missing required values."));
            return false;
        }

        var width = FormatDimensionValue(value.Width);
        declarations.Add(new KeyValuePair<string, string>($"{baseName}-width", width));
        declarations.Add(new KeyValuePair<string, string>($"{baseName}-style", value.Style));
        declarations.Add(new KeyValuePair<string, string>($"{baseName}-color", value.Color));
        declarations.Add(new KeyValuePair<string, string>($"{baseName}", $"{width} {value.Style} {value.Color}"));
        return true;
    }

    private static string? FormatDimensionTokenValue(DimensionTokenValue value)
    {
        return value.Value is null
            ? null
            : FormatDimension(value.Value.Value, value.Unit);
    }

    private static string? FormatDurationTokenValue(DurationTokenValue value)
    {
        return value.Value is null || string.IsNullOrWhiteSpace(value.Unit)
            ? null
            : $"{FormatDecimal(value.Value)}{value.Unit}";
    }

    private static string FormatDimensionValue(DimensionValue value) =>
        FormatDimension(value.Value, value.Unit);

    private static string FormatDimension(decimal value, string unit)
    {
        if (value == 0)
        {
            return "0";
        }

        return $"{FormatDecimal(value)}{unit}";
    }

    private static string FormatDecimal(decimal? value)
    {
        if (value is null)
        {
            return string.Empty;
        }

        return value.Value.ToString("0.############################", CultureInfo.InvariantCulture);
    }

    private static bool DimensionsEqual(DimensionValue left, DimensionValue right) =>
        left.Value == right.Value &&
        string.Equals(left.Unit, right.Unit, StringComparison.Ordinal);

    private static void AddMediaDeclaration(
        Dictionary<int, List<KeyValuePair<string, string>>> mediaDeclarations,
        int minWidthPx,
        string name,
        string value)
    {
        if (!mediaDeclarations.TryGetValue(minWidthPx, out var declarations))
        {
            declarations = [];
            mediaDeclarations[minWidthPx] = declarations;
        }

        declarations.Add(new KeyValuePair<string, string>(name, value));
    }
}
